plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'com.github.thejavalistener'
version = '2.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
}

tasks.withType(Javadoc).configureEach {
    options.encoding = 'UTF-8'
    options.charSet = 'UTF-8'
}

repositories {
    mavenCentral()
}

dependencies {

    // === PARTE DEL API ===
    api 'com.google.code.gson:gson:2.11.0'
    api 'com.google.zxing:core:3.5.2'
    api 'com.google.zxing:javase:3.5.2'

    // === IMPLEMENTACIÓN ===
    implementation 'org.reflections:reflections:0.10.2'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}


